import type { Metadata } from "next";
import "./globals.css";
import { italianno, manrope, roboto } from "./fonts";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${italianno.variable} ${manrope.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
